Numpy
= Number Python

Verarbeitung von Zahlen
Kann alles Mathematische
 - normale Funktionen
 - Berechnungen mit List

In [1]:
import numpy as np

Array

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

Nullbasierter Index

In [4]:
a[0]

np.int64(1)

In [5]:
a[1]

np.int64(2)

In [6]:
a[-1]

np.int64(5)

In [7]:
a[-2]

np.int64(4)

In [8]:
a[0:2]

array([1, 2])

In [9]:
a[1:-1]

array([2, 3, 4])

Eigenschaften

In [10]:
len(a) #mögliche Länge des Arrays

5

In [11]:
a.size #tatsächliche Anzahl der Elemente im Array

5

In [12]:
a.shape #handelt es sich um ein ein-, oder mehrdimensionales Array und welche Länge haben die Dimensionen

(5,)

In [13]:
a.ndim #wieviele Dimensionen

1

In [14]:
a.dtype

dtype('int64')

# Datentypen: #

## Ganzzahlen: ##
 - int8
 - int16
 - int32
 - int64 Standart
## Kommazahlen ##
 - float16
 - float32
 - float64

In [15]:
x=np.array([4.5,5.6])

In [16]:
x.dtype

dtype('float64')

Datentyp für array in numpy angeben


In [17]:
b = np.array([4,3,5], dtype=np.int8)

In [18]:
b

array([4, 3, 5], dtype=int8)

# Matrix #
=2 dimensionales Array oder Tabelle

In [19]:
c = np.array([[1,3,3], [1,3,4],[3,3,5]])

In [20]:
c

array([[1, 3, 3],
       [1, 3, 4],
       [3, 3, 5]])

Funktionen und Eigenschaften funktionieren gleich wie bei den eindimensonalen Arrays

In [21]:
c.sum()

np.int64(26)

In [22]:
c.mean()

np.float64(2.888888888888889)

In [23]:
c.sum(axis=0) # Senkrecht

array([ 5,  9, 12])

In [24]:
c.sum(axis=1) # waagrecht

array([ 7,  8, 11])

## mit Numpy Bereiche erstellen ##

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [27]:
d=np.arange(50,101)

In [28]:
d

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

## Index bei Matritzen ##

In [29]:
c

array([[1, 3, 3],
       [1, 3, 4],
       [3, 3, 5]])

In [30]:
c[0]

array([1, 3, 3])

In [31]:
c[1]

array([1, 3, 4])

In [33]:
c[0:2]

array([[1, 3, 3],
       [1, 3, 4]])

In [34]:
c[1:]

array([[1, 3, 4],
       [3, 3, 5]])

In [35]:
c[:2]

array([[1, 3, 3],
       [1, 3, 4]])

In [36]:
c[0][0]

np.int64(1)

In [37]:
c[0][1]

np.int64(3)

In [39]:
c[0,1] # andere Schreibweise für Zugriff nur in numpy möglich

np.int64(3)

In [40]:
c[0:3,0]

array([1, 1, 3])

In [41]:
c[0:3,1]

array([3, 3, 3])

In [42]:
c[0:,0]

array([1, 1, 3])

In [43]:
c[:3,0]

array([1, 1, 3])

In [44]:
c[:,0]

array([1, 1, 3])

In [45]:
c[1:,1:]

array([[3, 4],
       [3, 5]])

# Vektorisierung #
Gesamtes Array mit einer Operation ansprechen
Beliebge Operationen auf jedes Element des Arrays benutzen

In [66]:
d = np.arange(0,20)

In [67]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
d+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [69]:
d/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

Zwei Array miteinander Vektorisieren

In [70]:
e = np.arange(10,30)

In [74]:
e

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [72]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
d*e

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171, 200, 231, 264,
       299, 336, 375, 416, 459, 504, 551])

## Boolean Masken ##
Ergebnis einer Vektorisierung mit einem booleschen Operator

Im Endeffekt ein Array mit True/False

Wird immer für Filterungen verwendet

In [75]:
f = np.arange(10)

In [76]:
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
g = f>5

In [78]:
g


array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [79]:
f[g]

array([6, 7, 8, 9])

In [81]:
f[f>5] # schnellere Schreibweise

array([6, 7, 8, 9])

In [82]:
f[f%2==0]

array([0, 2, 4, 6, 8])

## Zusätzliche Funktionen ##

In [86]:
np.random.random() # Kommazahl zwischen 0 und 1

0.29935833082685614

In [87]:
np.random.random(size=(10)) # Array mit 10 zufälligen Kommazahlen

array([0.019924  , 0.6706161 , 0.29613191, 0.07745135, 0.30117087,
       0.59407852, 0.04939068, 0.49489491, 0.19346529, 0.87828937])

In [88]:
np.random.random(size=(5,5))

array([[0.97513966, 0.86957929, 0.11712441, 0.03397363, 0.48531466],
       [0.5326164 , 0.79159531, 0.36016744, 0.16870172, 0.75055864],
       [0.06705386, 0.21330571, 0.11707282, 0.72386746, 0.9452561 ],
       [0.85235978, 0.77497171, 0.64158821, 0.08620134, 0.96998472],
       [0.01917924, 0.02875014, 0.90480896, 0.19631227, 0.59465567]])

In [93]:
np.random.randint(10)

6

In [103]:
np.random.randint(10, size=(3, 5))


array([[4, 2, 1, 5, 7],
       [7, 4, 9, 5, 5],
       [3, 1, 0, 2, 9]], dtype=int32)

## reshape ##

Form eines Arrays verändern (1D -> 2D, 2D -> 1D)

In [104]:
h = np.random.randint(10, size=(10,5))

In [105]:
h

array([[8, 2, 7, 8, 5],
       [6, 2, 5, 4, 4],
       [5, 9, 3, 9, 9],
       [1, 2, 6, 2, 4],
       [0, 6, 5, 1, 4],
       [2, 0, 2, 0, 4],
       [8, 4, 9, 7, 7],
       [5, 6, 0, 9, 0],
       [9, 8, 3, 0, 5],
       [7, 8, 9, 8, 6]], dtype=int32)

In [106]:
h.reshape(5,10)

array([[8, 2, 7, 8, 5, 6, 2, 5, 4, 4],
       [5, 9, 3, 9, 9, 1, 2, 6, 2, 4],
       [0, 6, 5, 1, 4, 2, 0, 2, 0, 4],
       [8, 4, 9, 7, 7, 5, 6, 0, 9, 0],
       [9, 8, 3, 0, 5, 7, 8, 9, 8, 6]], dtype=int32)

In [107]:
h.reshape(50)

array([8, 2, 7, 8, 5, 6, 2, 5, 4, 4, 5, 9, 3, 9, 9, 1, 2, 6, 2, 4, 0, 6,
       5, 1, 4, 2, 0, 2, 0, 4, 8, 4, 9, 7, 7, 5, 6, 0, 9, 0, 9, 8, 3, 0,
       5, 7, 8, 9, 8, 6], dtype=int32)

In [108]:
h.reshape(h.size)

array([8, 2, 7, 8, 5, 6, 2, 5, 4, 4, 5, 9, 3, 9, 9, 1, 2, 6, 2, 4, 0, 6,
       5, 1, 4, 2, 0, 2, 0, 4, 8, 4, 9, 7, 7, 5, 6, 0, 9, 0, 9, 8, 3, 0,
       5, 7, 8, 9, 8, 6], dtype=int32)

In [109]:
h.reshape(-1)

array([8, 2, 7, 8, 5, 6, 2, 5, 4, 4, 5, 9, 3, 9, 9, 1, 2, 6, 2, 4, 0, 6,
       5, 1, 4, 2, 0, 2, 0, 4, 8, 4, 9, 7, 7, 5, 6, 0, 9, 0, 9, 8, 3, 0,
       5, 7, 8, 9, 8, 6], dtype=int32)

In [110]:
i = np.arange(27)

In [111]:
i

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [113]:
i.reshape(3,3)

ValueError: cannot reshape array of size 27 into shape (3,3)

reshape funktioniert nur, wenn die Anzahl der Elemente zu dem neuen Array passt.

In [114]:
i = np.arange(25)

In [115]:
i

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [116]:
i.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])