Numpy
= Number Python

Verarbeitung von Zahlen
Kann alles Mathematische
 - normale Funktionen
 - Berechnungen mit List

In [74]:
import numpy as np

Array

In [75]:
a = np.array([1,2,3,4,5])

In [76]:
a

array([1, 2, 3, 4, 5])

Nullbasierter Index

In [77]:
a[0]

np.int64(1)

In [78]:
a[1]

np.int64(2)

In [79]:
a[-1]

np.int64(5)

In [80]:
a[-2]

np.int64(4)

In [81]:
a[0:2]

array([1, 2])

In [82]:
a[1:-1]

array([2, 3, 4])

Eigenschaften

In [83]:
len(a) #mögliche Länge des Arrays

5

In [84]:
a.size #tatsächliche Anzahl der Elemente im Array

5

In [85]:
a.shape #handelt es sich um ein ein-, oder mehrdimensionales Array und welche Länge haben die Dimensionen

(5,)

In [86]:
a.ndim #wieviele Dimensionen

1

In [87]:
a.dtype

dtype('int64')

# Datentypen: #

## Ganzzahlen: ##
 - int8
 - int16
 - int32
 - int64 Standart
## Kommazahlen ##
 - float16
 - float32
 - float64

In [88]:
x=np.array([4.5,5.6])

In [89]:
x.dtype

dtype('float64')

Datentyp für array in numpy angeben


In [90]:
b = np.array([4,3,5], dtype=np.int8)

In [91]:
b

array([4, 3, 5], dtype=int8)

# Matrix #
=2 dimensionales Array oder Tabelle

In [92]:
c = np.array([[1,3,3], [1,3,4],[3,3,5]])

In [93]:
c

array([[1, 3, 3],
       [1, 3, 4],
       [3, 3, 5]])

Funktionen und Eigenschaften funktionieren gleich wie bei den eindimensonalen Arrays

In [94]:
c.sum()

np.int64(26)

In [95]:
c.mean()

np.float64(2.888888888888889)

In [96]:
c.sum(axis=0) # Senkrecht

array([ 5,  9, 12])

In [97]:
c.sum(axis=1) # waagrecht

array([ 7,  8, 11])

## mit Numpy Bereiche erstellen ##

In [98]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [100]:
d=np.arange(50,101)

In [101]:
d

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

## Index bei Matritzen ##

In [102]:
c

array([[1, 3, 3],
       [1, 3, 4],
       [3, 3, 5]])

In [103]:
c[0]

array([1, 3, 3])

In [104]:
c[1]

array([1, 3, 4])

In [105]:
c[0:2]

array([[1, 3, 3],
       [1, 3, 4]])

In [106]:
c[1:]

array([[1, 3, 4],
       [3, 3, 5]])

In [107]:
c[:2]

array([[1, 3, 3],
       [1, 3, 4]])

In [108]:
c[0][0]

np.int64(1)

In [109]:
c[0][1]

np.int64(3)

In [110]:
c[0,1] # andere Schreibweise für Zugriff nur in numpy möglich

np.int64(3)

In [111]:
c[0:3,0]

array([1, 1, 3])

In [112]:
c[0:3,1]

array([3, 3, 3])

In [113]:
c[0:,0]

array([1, 1, 3])

In [114]:
c[:3,0]

array([1, 1, 3])

In [115]:
c[:,0]

array([1, 1, 3])

In [116]:
c[1:,1:]

array([[3, 4],
       [3, 5]])

# Vektorisierung #
Gesamtes Array mit einer Operation ansprechen
Beliebge Operationen auf jedes Element des Arrays benutzen

In [117]:
d = np.arange(0,20)

In [118]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [119]:
d+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [120]:
d/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

Zwei Array miteinander Vektorisieren

In [121]:
e = np.arange(10,30)

In [122]:
e

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [123]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [124]:
d*e

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171, 200, 231, 264,
       299, 336, 375, 416, 459, 504, 551])

## Boolean Masken ##
Ergebnis einer Vektorisierung mit einem booleschen Operator

Im Endeffekt ein Array mit True/False

Wird immer für Filterungen verwendet

In [125]:
f = np.arange(10)

In [126]:
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
g = f>5

In [128]:
g


array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [129]:
f[g]

array([6, 7, 8, 9])

In [130]:
f[f>5] # schnellere Schreibweise

array([6, 7, 8, 9])

In [131]:
f[f%2==0]

array([0, 2, 4, 6, 8])

# Zusätzliche Funktionen

In [132]:
np.random.random() # Kommazahl zwischen 0 und 1

0.7868365315413948

In [133]:
np.random.random(size=(10)) # Array mit 10 zufälligen Kommazahlen

array([0.61183308, 0.19579919, 0.53749301, 0.89329354, 0.95043344,
       0.25270754, 0.18039292, 0.30842819, 0.69811116, 0.12078776])

In [134]:
np.random.random(size=(5,5))

array([[1.13932253e-01, 6.28661072e-01, 9.12670262e-01, 6.40250535e-04,
        2.28218503e-01],
       [1.09448091e-01, 1.80444339e-01, 9.31842622e-01, 7.50874859e-01,
        3.75471110e-01],
       [8.03649647e-01, 6.26343150e-01, 6.89767954e-01, 7.18333079e-01,
        4.78821840e-01],
       [9.28713207e-01, 8.81476420e-01, 8.14679468e-01, 9.02497880e-01,
        5.75344353e-01],
       [4.63421037e-02, 5.55325801e-01, 5.89037914e-02, 5.41070856e-01,
        4.74234611e-01]])

In [135]:
np.random.randint(10)

1

In [136]:
np.random.randint(10, size=(3, 5))


array([[5, 8, 2, 9, 9],
       [2, 2, 7, 3, 8],
       [3, 6, 2, 6, 2]], dtype=int32)

## reshape ##

Form eines Arrays verändern (1D -> 2D, 2D -> 1D)

In [137]:
h = np.random.randint(10, size=(10,5))

In [138]:
h

array([[8, 5, 4, 1, 0],
       [4, 8, 1, 2, 9],
       [7, 8, 0, 5, 8],
       [8, 1, 6, 2, 1],
       [7, 2, 4, 4, 8],
       [9, 8, 9, 2, 7],
       [8, 2, 8, 0, 6],
       [6, 6, 1, 2, 4],
       [0, 9, 4, 7, 3],
       [1, 3, 2, 5, 7]], dtype=int32)

In [139]:
h.reshape(5,10)

array([[8, 5, 4, 1, 0, 4, 8, 1, 2, 9],
       [7, 8, 0, 5, 8, 8, 1, 6, 2, 1],
       [7, 2, 4, 4, 8, 9, 8, 9, 2, 7],
       [8, 2, 8, 0, 6, 6, 6, 1, 2, 4],
       [0, 9, 4, 7, 3, 1, 3, 2, 5, 7]], dtype=int32)

In [140]:
h.reshape(50)

array([8, 5, 4, 1, 0, 4, 8, 1, 2, 9, 7, 8, 0, 5, 8, 8, 1, 6, 2, 1, 7, 2,
       4, 4, 8, 9, 8, 9, 2, 7, 8, 2, 8, 0, 6, 6, 6, 1, 2, 4, 0, 9, 4, 7,
       3, 1, 3, 2, 5, 7], dtype=int32)

In [141]:
h.reshape(h.size)

array([8, 5, 4, 1, 0, 4, 8, 1, 2, 9, 7, 8, 0, 5, 8, 8, 1, 6, 2, 1, 7, 2,
       4, 4, 8, 9, 8, 9, 2, 7, 8, 2, 8, 0, 6, 6, 6, 1, 2, 4, 0, 9, 4, 7,
       3, 1, 3, 2, 5, 7], dtype=int32)

In [142]:
h.reshape(-1)

array([8, 5, 4, 1, 0, 4, 8, 1, 2, 9, 7, 8, 0, 5, 8, 8, 1, 6, 2, 1, 7, 2,
       4, 4, 8, 9, 8, 9, 2, 7, 8, 2, 8, 0, 6, 6, 6, 1, 2, 4, 0, 9, 4, 7,
       3, 1, 3, 2, 5, 7], dtype=int32)

In [143]:
i = np.arange(27)

In [144]:
i

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

i.reshape(3,3),

reshape funktioniert nur, wenn die Anzahl der Elemente zu dem neuen Array passt.

In [145]:
i = np.arange(25)

In [146]:
i

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [147]:
i.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## linspace
Erzeugt ein Array von X bis Y mit Z Element

Alle Abstände sind gleich groß.


In [148]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [149]:
np.linspace(0,20,201)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9,
       11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. ,
       12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1,
       13.2, 13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2,
       14.3, 14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15

## zeros, ones

In [150]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [151]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [152]:
j=np.zeros(10) == 0

In [153]:
j

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [154]:
k = np.zeros(5)==1

In [155]:
k

array([False, False, False, False, False])

In [156]:
np.concatenate((j, k))

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False])

In [157]:
j=np.array([[1,5],[4,3]])

In [158]:
j

array([[1, 5],
       [4, 3]])

In [159]:
k=np.array([[2,7],[6,9]])

In [160]:
k

array([[2, 7],
       [6, 9]])

In [161]:
np.concatenate((j, k), axis=0)

array([[1, 5],
       [4, 3],
       [2, 7],
       [6, 9]])

In [162]:
np.concatenate((j, k), axis=1)

array([[1, 5, 2, 7],
       [4, 3, 6, 9]])

In [167]:
np.arange(1,101, 0.5)

array([  1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,   4.5,   5. ,
         5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,   9.5,
        10. ,  10.5,  11. ,  11.5,  12. ,  12.5,  13. ,  13.5,  14. ,
        14.5,  15. ,  15.5,  16. ,  16.5,  17. ,  17.5,  18. ,  18.5,
        19. ,  19.5,  20. ,  20.5,  21. ,  21.5,  22. ,  22.5,  23. ,
        23.5,  24. ,  24.5,  25. ,  25.5,  26. ,  26.5,  27. ,  27.5,
        28. ,  28.5,  29. ,  29.5,  30. ,  30.5,  31. ,  31.5,  32. ,
        32.5,  33. ,  33.5,  34. ,  34.5,  35. ,  35.5,  36. ,  36.5,
        37. ,  37.5,  38. ,  38.5,  39. ,  39.5,  40. ,  40.5,  41. ,
        41.5,  42. ,  42.5,  43. ,  43.5,  44. ,  44.5,  45. ,  45.5,
        46. ,  46.5,  47. ,  47.5,  48. ,  48.5,  49. ,  49.5,  50. ,
        50.5,  51. ,  51.5,  52. ,  52.5,  53. ,  53.5,  54. ,  54.5,
        55. ,  55.5,  56. ,  56.5,  57. ,  57.5,  58. ,  58.5,  59. ,
        59.5,  60. ,  60.5,  61. ,  61.5,  62. ,  62.5,  63. ,  63.5,
        64. ,  64.5,